<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="/phalcon_auth/public/css/style.css">
</head>
<body>

<div class="container">

    <div class="form-box">

        <img src="/phalcon_auth/public/images/logo.png" class="logo">

        <h2>Login</h2>

        <form method="POST">

            <input type="email" name="email" placeholder="Enter Email" required>

            <input type="password" name="password" placeholder="Enter Password" required>

            <button type="submit">Login</button>

        </form>

        <p>
            Don't have account?
            <a href="/auth/register">Register</a>
        </p>

    </div>

</div>

</body>
</html>