<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
    <link rel="stylesheet" href="/phalcon_auth/public/css/style.css">
</head>
<body>

<div class="container">

    <div class="form-box">

        <img src="/phalcon_auth/public/images/OIP.webp" class="logo">

        <h2>Register</h2>

        <form method="POST">

            <input type="text" name="name" placeholder="Enter Name" required>

            <input type="email" name="email" placeholder="Enter Email" required>

            <input type="password" name="password" placeholder="Enter Password" required>

            <button type="submit">Register</button>

        </form>

        <p>
            Already have account?
            <a href="/auth/login">Login</a>
        </p>

    </div>

</div>

</body>
</html>